### ISSUE TITLE
HAL_CAN_Init() conflict with Renode

### ISSUE THREAD

**Issue by abhat090** [UCR-FSAE/24E_BMU#19]
Currently there is a issue where the initialization of CAN results in a timeout error when run through renode, this prevents any code from running and ends in an error callback_loop.

Need to figure out some way to either safely bypass the loop specifically in renode or figure out someway to make renode ground the can protocol or link it somewhere.

**Comment by binaryclock01** [comment]
Did you ever find a solution for this? I'm having the same issue, even after creating a virtual can bus and linking `sysbus.can1` and `sysbus.can2` to it.  I'm quiet new to renode, so maybe I'm doing something wrong. I'll update if I find the solution.  Here's my process:

**Commands in renode:**

```
emulation CreateCANHub "canHub"
mach create
include @platforms/cpus/stm32f4.repl
connector Connect sysbus.can1 canHub
connector Connect sysbus.can2 canHub
sysbus LoadELF "firmware.elf"
machine StartGdbServer 3333
start
```

**In gdb:**

```
(gdb) bt
#0  0x08000390 in HAL_CAN_Init (hcan=hcan@entry=0x2001d574 <hcan1>)
    at /root/.platformio/packages/framework-stm32cubef4/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c:340
#1  0x080074c4 in MX_CAN1_Init () at src/main.c:430
#2  0x08007610 in main (argc=<optimized out>, argv=<optimized out>)
    at src/main.c:246
```

**main.c**

```
430    if (HAL_CAN_Init(&hcan1) != HAL_OK)
431    {
432       Error_Handler();
433    }
```

It works just fine outside of renode on my stm32 nucleo board when the CAN BUS is powered.
